services:
  ## AuthOnchain (Development Environment)
  authonchain:
    build: .
    image: authonchain/authonchain:develop
    # Expose HTTP port and debug port
    ports:
      - "8080:8080"   # Default HTTP port (host:container)
      - "40000:40000" # Go Debugger (host:container)
    ## Configure development environment
    environment:
      AUTHONCHAIN_DEFAULT_USER: "default"
      AUTHONCHAIN_DEFAULT_PASSWORD: "password"
      AUTHONCHAIN_HTTP_HOST: "0.0.0.0"
      AUTHONCHAIN_HTTP_PORT: 8080
      AUTHONCHAIN_ASSETS_PATH: "/go/src/github.com/Le-BlitzZz/onchain-auth-app/assets"
    working_dir: "/go/src/github.com/Le-BlitzZz/onchain-auth-app"
    volumes:
      - ".:/go/src/github.com/Le-BlitzZz/onchain-auth-app"
      - "go-mod:/go/pkg/mod"

## Create named volume for Go module cache
volumes:
  go-mod:
    driver: local
